sonar.projectKey=MathiasKawte_Semana11_SistemasInteligentesTarea
sonar.organization=mathiaskawte
sonar.projectName=Semana11_SistemasInteligentesTarea
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8